version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/seemee-api/
hooks:
  BeforeInstall:
    - location: deploy-scripts/install_dependencies.sh
      timeout: 300
      # runas: ubuntu
  AfterInstall:
    - location: deploy-scripts/deploy_laravel.sh
      timeout: 300
      # runas: ubuntu
  ApplicationStart:
    - location: deploy-scripts/run_laradock_commands.sh
      timeout: 300
      # runas: ubuntu
